### ISSUE TITLE
Requesting feature assistivetouch Enable and disable

### ISSUE THREAD

**Issue by krishtoautomate** [appium/appium-ios-device#122]
iphone supports enable and disable of assistive touch by parsing boolean to com.apple.Accessibility.AssistiveTouchEnabledByiTunes

tools like tidevice already implemented and it is nice to have in webdriveragent with api control.

**Comment by KazuCocoa** [comment]
btw, what is the purpose for the assistive touch?
I know of the method, but I'm keen to know of the use-case since the assistive touch's materials are not interactable via automation. To turn it off in automation? @krishtoautomate

**Comment by krishtoautomate** [comment]
one of the use case is appSwitcher can be accessible only when assistiveTouch is enabled which ll expose shotcut to appSwitcher window.

**Comment by krishtoautomate** [comment]
why cannot it be part of webdriveragent? cant we call this api from inside phone?

**Comment by KazuCocoa** [comment]
Correct, afaik, it cannot

**Comment by KazuCocoa** [comment]
Btw, maybe the appSwitcher shortcut can tap via manual interaction so far, not via Appium/WDA

**Comment by krishtoautomate** [comment]
Understood. We can close this, if this cant help appSwitcher accessibility
