### ISSUE TITLE
IOS 18.1 XCode 16.0 - Failed to start Simulate Location Service: Failed to receive any data within the timeout: 5000 

### ISSUE THREAD

**Issue by wtfchewy** [appium/appium-ios-device#186]
I am attempting the change the location of my device running IOS 18.1 that is connected to my MacBook using the following code and each time I attempt I get the following console logs. Apologies in advance if I did something wrong!

`Connected device UDID: (insert my UDID for my phone here)
Attempting to start Simulate Location Service...
Failed to start Simulate Location Service: Failed to receive any data within the timeout: 5000`

(code im attempting to use)
https://gist.github.com/wtfchewy/67db2a64f0bbed9977d6908f02f1e66b

**Comment by tomriddly** [comment]
developer image mounted is required before simulating location. And after iOS 17, Apple changed developer image mounting, we could not use the new protocol on nodejs for now. You could try to use the same api in python from [doronz88/pymobiledevice3](https://github.com/doronz88/pymobiledevice3 ) with `start-tunnel` and `--rsd`. We will try to fix this after `quic` is a formal feature in nodejs.
