### ISSUE TITLE
getDeviceTime throws exception even when a valid time is returned

### ISSUE THREAD

**Issue by nurdtechie98** [appium/appium-ios-device#77]
The getDeviceTime method fetches the time using plist services, 
when fetching the [utcOffset](https://github.com/appium/appium-ios-device/blob/a739ac37a0410af21fc95a34d60f6cbfb555bac3/lib/utilities.js#L98) for the devices it breaks with an exception:
```
Encountered internal error running command: Error: Unexpected data: {"Key":"TimeZoneOffsetFromUTC","Request":"GetValue","Value":0}
     at Lockdown.getValue (/usr/local/appium_1.15.0/node_modules/appium-ios-device/lib/lockdown/index.js:85:13)
```
Ways to reproduce:
* use on any appium greater than and equal to 1.15 on real devices in GMT+0 timezone region
* `driver.device_time`

Reason:
This doesn’t happens usually, but for devices in UTC zone because, here the actual  TimeZoneOffsetFromUTC is 0 as they fall in the GMT zone.
causing this [check](https://github.com/appium/appium-ios-device/blob/a739ac37a0410af21fc95a34d60f6cbfb555bac3/lib/lockdown/index.js#L80) to fail as data.value is actually 0, thus raising an exception.

**Comment by mykola-mokhnach** [comment]
The fix is published to appium@beta
