### ISSUE TITLE
feat: Add instruments service

### ISSUE THREAD

**Issue by YueChen-C** [appium/appium-ios-device#85]
Adapted from https://github.com/YueChen-C/py-ios-device to  https://github.com/appium/appium-ios-device
I have completed 90% of the work for the instruments protocol.  And the test is successful above version 14. you can get `fps`, `performance`, `netstat`, etc.
but i have a problem on devices under version 14. After the ssl protocol is successfully handshake, I need to close the ssl protocol channel and use clear text transmission. I searched a lot of information, but I couldn't succeed.

Python:
https://github.com/YueChen-C/py-ios-device/blob/71267a1ac472db53fa84497312f0a4cdc0fdee17/ios_device/servers/Instrument.py#L29

nodejs:
https://github.com/YueChen-C/appium-ios-device/blob/b6f0fb42258f04ecc28509f756b089412b440db8/lib/services.js#L89

@KazuCocoa @mykola-mokhnach Could you spare some time to help me ？

**Comment by mykola-mokhnach** [comment]
Let me check. I don't have much knowledge about that, but probably I can help something after checking this code.

It would be great if @umutuzgur or @dvdmssmnn could share their knowledge.

**Comment by mykola-mokhnach** [comment]
I assume you could first create a raw socket connection and then call [upgradeToSSL](https://github.com/appium/appium-ios-device/blob/861569a4cca7cd8ccdabd0ac399fb8ce5ef3b52b/lib/ssl-helper.js#L6) on it. The following commands could be still sent to the initial socket instead of the wrapped one if you want then to go unencrypted.

**Comment by mykola-mokhnach** [comment]
As far as I can see this should/may be handled automatically: https://github.com/appium/appium-ios-device/blob/861569a4cca7cd8ccdabd0ac399fb8ce5ef3b52b/lib/services.js#L87

**Comment by KazuCocoa** [comment]
Yea, my understanding for ssl/non-ssl is `EnableServiceSSL` in its initial lockdown handshake.
It seems like instruments service differ from existing service's ssl(?). The `EnableServiceSSL` should be true over ios 13.

Then, probably we need to add an option to skip 
https://github.com/appium/appium-ios-device/blob/71be21118d71a7c7089ebc521d1cbd1ee7669ed3/lib/utilities.js#L151 for instrument?

**Comment by dvdmssmnn** [comment]
> After the ssl protocol is successfully handshake, I need to close the ssl protocol channel and use clear text transmission. I searched a lot of information, but I couldn't succeed.

Not sure if I get the question right. From what I understand you pretty much understood already what's going on with the services that do a SSL handshake, but continue the communication in plaintext.

And as @mykola-mokhnach said
> I assume you could first create a raw socket connection and then call [upgradeToSSL](https://github.com/appium/appium-ios-device/blob/861569a4cca7cd8ccdabd0ac399fb8ce5ef3b52b/lib/ssl-helper.js#L6) on it. The following commands could be still sent to the initial socket instead of the wrapped one if you want them to go unencrypted.

that should do  the trick.

I can only point to the project https://github.com/danielpaulus/go-ios/ (which is anyways a great reference for everything in that area 🙂 )

There are a few services that behave like this: https://github.com/danielpaulus/go-ios/blob/a84a0cfbb66273ee78878bc0719451d389231b35/ios/connect.go#L49

And the handshake only part is done here:
https://github.com/danielpaulus/go-ios/blob/a84a0cfbb66273ee78878bc0719451d389231b35/ios/deviceconnection.go#L167

**Comment by YueChen-C** [comment]
I tried it before,but it doesn't work.
> I assume you could first create a raw socket connection and then call [upgradeToSSL](https://github.com/appium/appium-ios-device/blob/861569a4cca7cd8ccdabd0ac399fb8ce5ef3b52b/lib/ssl-helper.js#L6) on it. The following commands could be still sent to the initial socket instead of the wrapped one if you want them to go unencrypted.

Through packet capture analysis.  call [upgradeToSSL](https://github.com/appium/appium-ios-device/blob/861569a4cca7cd8ccdabd0ac399fb8ce5ef3b52b/lib/ssl-helper.js#L6) does not start the ssl handshake. The ssl handshake is not started until data needs to be sent.
And after the ssl handshake is successful, the service will immediately return plaintext data instead of encrypted data, which will cause the socket to disconnect.

Is there a way to send and receive only ssl handshake packets?
@mykola-mokhnach @dvdmssmnn @KazuCocoa

**Comment by mykola-mokhnach** [comment]
I assume this needs some experimenting. I would try to call https://nodejs.org/api/tls.html#tlssocketrenegotiateoptions-callback or https://nodejs.org/api/net.html#socketconnect on the TLSSocket object and then continue sending data over the inital raw socket. Also, the TLSSocket has a non-documented [destroySSL method](https://github.com/nodejs/node/blob/a987ba16f8cb052420694d74b898166cd7b32783/lib/_tls_wrap.js#L649 ). Maybe this is something that you need

**Comment by mykola-mokhnach** [comment]
In the worst case we can just drop the support of devices below iOS 14 🤷

**Comment by mykola-mokhnach** [comment]
@YueChen-C Thanks for adding the new service. Do you have any plans about creating wrappers over other py-ios-device features, like profiles management, performance counters, etc?
